# Generated by Django 5.2.8 on 2025-12-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('road_issue', 'Road Issue'), ('electricity', 'Electricity'), ('water_supply', 'Water Supply'), ('garbage', 'Garbage Problem'), ('traffic', 'Traffic Jam'), ('street_light', 'Street Light'), ('internet', 'Internet Issue'), ('gas', 'Gas Problem'), ('drainage', 'Drainage Issue'), ('public_safety', 'Public Safety'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complain_image/')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('rejected', 'REJECTED')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplainResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='village.complain')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_image/')),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cultural', 'Cultural Event'), ('sports', 'Sports Event'), ('religious', 'Religious Event'), ('education', 'Educational Program'), ('health', 'Health Camp'), ('festival', 'Village Festival'), ('meeting', 'Public Meeting'), ('training', 'Training Workshop'), ('youth', 'Youth Program'), ('awareness', 'Awareness Campaign')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
