# Generated by Django 5.2.8 on 2025-12-10 10:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=cloudinary.models.CloudinaryField(default='0', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(default='Pending', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
