# Generated by Django 5.2.8 on 2025-12-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
