# Generated by Django 5.2.8 on 2025-12-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural Event'), ('sports', 'Sports Event'), ('religious', 'Religious Event'), ('education', 'Educational Program'), ('health', 'Health Camp'), ('festival', 'Village Festival'), ('meeting', 'Public Meeting'), ('training', 'Training Workshop'), ('youth', 'Youth Program'), ('awareness', 'Awareness Campaign')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_image/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
