# Generated by Django 5.2.8 on 2026-01-03 15:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_alter_complain_image_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='complain_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='event_image'),
        ),
    ]
