# Generated by Django 5.2.8 on 2026-09-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_alter_complain_image_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
