# Generated by Django 5.2.8 on 2025-12-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_polls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polls',
        ),
    ]
