# Generated by Django 5.2.8 on 2025-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_delete_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('post_code', models.CharField(default='0000', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='village_image/')),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('head_of_village', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('total_voters', models.IntegerField(default=0)),
                ('literacy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('area_sq_km', models.FloatField(blank=True, help_text='Village area in square kilometers', null=True)),
                ('number_of_houses', models.IntegerField(blank=True, null=True)),
                ('number_of_schools', models.IntegerField(blank=True, null=True)),
                ('number_of_health_centers', models.IntegerField(blank=True, null=True)),
                ('number_of_markets', models.IntegerField(blank=True, null=True)),
                ('number_of_religious_places', models.IntegerField(blank=True, null=True)),
                ('number_of_community_centers', models.IntegerField(blank=True, null=True)),
                ('has_electricity', models.BooleanField(default=True)),
                ('has_clean_water', models.BooleanField(default=True)),
                ('has_internet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
