# Generated by Django 5.2.8 on 2026-01-03 15:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_village_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='village_image'),
        ),
    ]
