# Generated by Django 5.2.8 on 2025-12-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profession_image/')),
                ('description', models.TextField()),
                ('profession', models.CharField(choices=[('bussinessman', 'Bussinessman'), ('software_engineer', 'Software Engineer'), ('software_developer', 'Software Developer'), ('freelancer', 'Freelancer'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('student', 'Student'), ('nurse', 'Nurse'), ('farmer', 'Farmer'), ('mechanic', 'Mechanic'), ('designer', 'Designer'), ('data_scientist', 'Data Scientist'), ('defense', 'Defense'), ('lawyer', 'Lawyer'), ('accountant', 'Accountant'), ('artist', 'Artist'), ('chef', 'Chef'), ('photographer', 'Photographer'), ('journalist', 'Journalist'), ('driver', 'Driver'), ('pilot', 'Pilot'), ('engineer', 'Engineer')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profession_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
