# Generated by Django 5.2.8 on 2025-12-10 10:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionuser',
            name='image',
            field=cloudinary.models.CloudinaryField(default=True, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
