# Generated by Django 5.2.8 on 2026-01-03 15:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0002_alter_professionuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionuser',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='professionUser_image'),
        ),
    ]
