# Generated by Django 5.2.8 on 2026-09-07 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0003_alter_professionuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2020, 1, 15)),
            preserve_default=False,
        ),
    ]
