# Generated by Django 5.2.8 on 2026-09-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0004_professionuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionuser',
            name='created_at',
        ),
    ]
