# Generated by Django 5.2.8 on 2026-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('bussinessman', 'Bussinessman'), ('entrepreneur', 'Entrepreneur'), ('software_engineer', 'Software Engineer'), ('software_developer', 'Software Developer'), ('freelancer', 'Freelancer'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('student', 'Student'), ('nurse', 'Nurse'), ('farmer', 'Farmer'), ('mechanic', 'Mechanic'), ('designer', 'Designer'), ('data_scientist', 'Data Scientist'), ('defense', 'Defense'), ('lawyer', 'Lawyer'), ('accountant', 'Accountant'), ('artist', 'Artist'), ('chef', 'Chef'), ('photographer', 'Photographer'), ('journalist', 'Journalist'), ('driver', 'Driver'), ('pilot', 'Pilot'), ('engineer', 'Engineer'), ('housewife', 'Housewife')], max_length=50, null=True),
        ),
    ]
