# Generated by Django 5.2.8 on 2026-09-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_bio_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('bussinessman', 'Bussinessman'), ('entrepreneur', 'Entrepreneur'), ('software_engineer', 'Software Engineer'), ('software_developer', 'Software Developer'), ('freelancer', 'Freelancer'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('student', 'Student'), ('nurse', 'Nurse'), ('farmer', 'Farmer'), ('mechanic', 'Mechanic'), ('designer', 'Designer'), ('data_scientist', 'Data Scientist'), ('defense', 'Defense'), ('lawyer', 'Lawyer'), ('accountant', 'Accountant'), ('artist', 'Artist'), ('chef', 'Chef'), ('photographer', 'Photographer'), ('journalist', 'Journalist'), ('driver', 'Driver'), ('pilot', 'Pilot'), ('engineer', 'Engineer'), ('housewife', 'Housewife')], default='software_developer', max_length=50),
            preserve_default=False,
        ),
    ]
