# Generated by Django 5.2.8 on 2025-12-01 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinik_image/')),
                ('type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('ngo', 'NGO')], default='private', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University')], default='school', max_length=20)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='institute_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_image/')),
                ('specialization', models.CharField()),
                ('clinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='institute.clinik')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='institute.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_image/')),
                ('grade', models.CharField(max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institute.institution')),
            ],
        ),
    ]
